### ISSUE TITLE
Update to run on py27

### ISSUE THREAD

**Issue by GoogleCodeExporter** [acdha/pymacadmin#10]
```
Nothing was holding on to the handlers after the loop ends, so they were being 
release before the notification fired. This is a problem with py27, which seems 
to have ARC enabled.

Also, the NS prefix is reserved for Apple use, so rename NSNotificationHandler 
to NotificationHandler
```

Original issue reported on code.google.com by `crc@google.com` on 21 Jan 2014 at 9:05

Attachments:
* [crankd.py.patch](https://storage.googleapis.com/google-code-attachments/pymacadmin/issue-10/comment-0/crankd.py.patch)

**Comment by acdha** [comment]
This issue was moved to MacSysadmin/pymacadmin#10
